# Generated by Django 2.1 on 2018-08-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.CharField(max_length=255, verbose_name='Gene')),
                ('tf_id', models.CharField(max_length=255, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('matrix', models.TextField(max_length=10000, verbose_name='Matriz')),
                ('motifs', models.CharField(max_length=10000, verbose_name='Motivos')),
                ('reverseComplement', models.CharField(max_length=10000, verbose_name='Complemento reverso')),
                ('upstream', models.TextField(max_length=10000, verbose_name='5l3l')),
                ('downstream', models.TextField(max_length=10000, verbose_name='3l5l')),
                ('mean', models.FloatField(verbose_name='Média')),
                ('sumatory', models.IntegerField(verbose_name='Somatório')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'ordering': ['gene', 'tf_id', 'name'],
            },
        ),
    ]
