# Generated by Django 2.1 on 2018-08-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20180820_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('matrix', models.TextField(max_length=10000, verbose_name='Matriz')),
                ('motifs', models.CharField(max_length=10000, verbose_name='Motivos')),
                ('reverseComplement', models.CharField(max_length=10000, verbose_name='Complemento reverso')),
                ('genome', models.IntegerField(verbose_name='Genoma')),
            ],
            options={
                'verbose_name': 'Background',
                'verbose_name_plural': 'Backgrounds',
                'ordering': ['id', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='log',
            name='downstream',
            field=models.TextField(max_length=10000, verbose_name='Downstream'),
        ),
        migrations.AlterField(
            model_name='log',
            name='upstream',
            field=models.TextField(max_length=10000, verbose_name='Upstream'),
        ),
    ]
