# Generated by Django 2.1.2 on 2018-10-16 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('matrix', models.TextField(max_length=10000, verbose_name='Matriz')),
                ('motifs', models.CharField(max_length=10000, verbose_name='Motivos')),
                ('reverseComplement', models.CharField(max_length=10000, verbose_name='Complemento reverso')),
                ('vigna_genome', models.IntegerField(verbose_name='Genoma de Vigna')),
            ],
            options={
                'verbose_name': 'Background',
                'verbose_name_plural': 'Backgrounds',
                'ordering': ['family', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Família de fator de transcrição',
                'verbose_name_plural': 'Famílias de fatores de transcrição',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoter_id', models.CharField(max_length=255, null=True, verbose_name='Promotor')),
                ('upstream', models.TextField(blank=True, null=True, verbose_name='upstream')),
                ('downstream', models.TextField(blank=True, null=True, verbose_name='downstream')),
                ('mean', models.FloatField(blank=True, null=True, verbose_name='Média')),
                ('sumatory', models.IntegerField(blank=True, null=True, verbose_name='Somatório')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'ordering': ['promoter_id', 'tf'],
            },
        ),
        migrations.CreateModel(
            name='Promoter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locus', models.CharField(max_length=255, verbose_name='Locus')),
                ('size', models.IntegerField(verbose_name='Tamanho')),
                ('direction', models.CharField(max_length=255, verbose_name='Direção')),
                ('promoter', models.TextField(max_length=5001, verbose_name='Promotor')),
            ],
            options={
                'verbose_name': 'Promotor',
                'verbose_name_plural': 'Promotores',
                'ordering': ['specie', 'locus', 'direction'],
            },
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Espécie')),
            ],
            options={
                'verbose_name': 'Espécie',
                'verbose_name_plural': 'Espécies',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Transcriptor',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('matrix', models.TextField(max_length=10000, verbose_name='Matriz')),
                ('motifs', models.CharField(max_length=10000, verbose_name='Motivos')),
                ('reverseComplement', models.CharField(max_length=10000, verbose_name='Complemento reverso')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecr.Family', verbose_name='Família')),
            ],
            options={
                'verbose_name': 'Fator de transcrição',
                'verbose_name_plural': 'Fatores de transcrição',
                'ordering': ['family', 'id'],
            },
        ),
        migrations.AddField(
            model_name='promoter',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecr.Specie', verbose_name='Espécie'),
        ),
        migrations.AddField(
            model_name='log',
            name='tf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecr.Transcriptor', verbose_name='Fator de transcrição'),
        ),
        migrations.AddField(
            model_name='background',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecr.Family', verbose_name='Família'),
        ),
    ]
