# Generated by Django 2.1.2 on 2019-06-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='background',
            options={'ordering': ['id'], 'verbose_name': 'Background', 'verbose_name_plural': 'Backgrounds'},
        ),
        migrations.AddField(
            model_name='background',
            name='glycine_genome',
            field=models.IntegerField(default=0, verbose_name='Genoma de Glycine max'),
            preserve_default=False,
        ),
    ]
