# Generated by Django 2.1 on 2018-09-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='promoter',
            field=models.CharField(default=None, max_length=255, verbose_name='Promotor'),
            preserve_default=False,
        ),
    ]
