# Generated by Django 2.1 on 2018-09-14 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecr', '0002_auto_20180914_0604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['promoter_id', 'tf_id'], 'verbose_name': 'Log', 'verbose_name_plural': 'Logs'},
        ),
        migrations.RenameField(
            model_name='log',
            old_name='promoter',
            new_name='promoter_id',
        ),
    ]
