# Generated by Django 2.1.11 on 2020-02-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecr', '0003_auto_20190626_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='background',
            name='glycine_genome',
        ),
        migrations.RemoveField(
            model_name='background',
            name='vigna_genome',
        ),
        migrations.RemoveField(
            model_name='background',
            name='vitis_genome',
        ),
        migrations.AddField(
            model_name='background',
            name='arabidopsis_thaliana',
            field=models.IntegerField(default=0, verbose_name='Arabidopsis thaliana'),
        ),
        migrations.AddField(
            model_name='background',
            name='glycine_max',
            field=models.IntegerField(default=0, verbose_name='Glycine max'),
        ),
        migrations.AddField(
            model_name='background',
            name='hordeum_vulgare',
            field=models.IntegerField(default=0, verbose_name='Hordeum vulgare'),
        ),
        migrations.AddField(
            model_name='background',
            name='manihot_esculenta',
            field=models.IntegerField(default=0, verbose_name='Manihot esculenta'),
        ),
        migrations.AddField(
            model_name='background',
            name='medicago_truncatula',
            field=models.IntegerField(default=0, verbose_name='Medicago truncatula'),
        ),
        migrations.AddField(
            model_name='background',
            name='oryza_sativa',
            field=models.IntegerField(default=0, verbose_name='Oryza sativa'),
        ),
        migrations.AddField(
            model_name='background',
            name='phaseolus_vulgaris',
            field=models.IntegerField(default=0, verbose_name='Phaseolus vulgaris'),
        ),
        migrations.AddField(
            model_name='background',
            name='physcomitrella_patens',
            field=models.IntegerField(default=0, verbose_name='Physcomitrella patens'),
        ),
        migrations.AddField(
            model_name='background',
            name='ricinus_communis',
            field=models.IntegerField(default=0, verbose_name='Ricinus communis'),
        ),
        migrations.AddField(
            model_name='background',
            name='trifolium_pratense',
            field=models.IntegerField(default=0, verbose_name='Trifolium pratense'),
        ),
        migrations.AddField(
            model_name='background',
            name='vigna_unguiculata',
            field=models.IntegerField(default=0, verbose_name='Vigna unguiculata'),
        ),
        migrations.AddField(
            model_name='background',
            name='vitis_vinifera',
            field=models.IntegerField(default=0, verbose_name='Vitis vinifera'),
        ),
        migrations.AddField(
            model_name='background',
            name='zea_mays',
            field=models.IntegerField(default=0, verbose_name='Zea mays'),
        ),
    ]
