# Generated by Django 2.1 on 2018-09-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecr', '0003_auto_20180914_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='promoter_id',
            field=models.CharField(max_length=255, null=True, verbose_name='Promotor'),
        ),
    ]
