# Generated by Django 2.1 on 2018-08-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Espécie')),
            ],
            options={
                'verbose_name': 'Espécie',
                'verbose_name_plural': 'Espécies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Promoter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locus', models.CharField(max_length=255, verbose_name='Locus')),
                ('especie', models.CharField(max_length=255, verbose_name='Espécie')),
                ('size', models.IntegerField(verbose_name='Tamanho')),
                ('direction', models.CharField(max_length=255, verbose_name='Direção')),
                ('promoter', models.CharField(max_length=5001, verbose_name='Promotor')),
            ],
            options={
                'verbose_name': 'Promotor',
                'verbose_name_plural': 'Promotores',
                'ordering': ['especie', 'id', 'direction'],
            },
        ),
    ]
