# Generated by Django 2.1 on 2018-08-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promoter',
            options={'ordering': ['especie', 'locus', 'direction'], 'verbose_name': 'Promotor', 'verbose_name_plural': 'Promotores'},
        ),
        migrations.AlterField(
            model_name='promoter',
            name='promoter',
            field=models.TextField(max_length=5001, verbose_name='Promotor'),
        ),
    ]
