# Generated by Django 2.1 on 2018-08-13 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Família de fator de transcrição',
                'verbose_name_plural': 'Famílias de fatores de transcrição',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transcriptor',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('matrix', models.CharField(max_length=10000, verbose_name='Matriz')),
                ('motifs', models.CharField(max_length=10000, verbose_name='Motivos')),
                ('reverseComplement', models.CharField(max_length=10000, verbose_name='Complemento reverso')),
                ('family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transcriptors.Family', verbose_name='Família')),
            ],
            options={
                'verbose_name': 'Fator de transcrição',
                'verbose_name_plural': 'Fatores de transcrição',
                'ordering': ['family', 'id'],
            },
        ),
    ]
