# Generated by Django 2.1 on 2018-08-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Família de fator de transcrição',
                'verbose_name_plural': 'Famílias de fatores de transcrição',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transcriptor',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('family', models.CharField(blank=True, max_length=255, null=True, verbose_name='Família')),
                ('a', models.CharField(max_length=10000, verbose_name='A')),
                ('c', models.CharField(max_length=10000, verbose_name='C')),
                ('g', models.CharField(max_length=10000, verbose_name='G')),
                ('t', models.CharField(max_length=10000, verbose_name='T')),
                ('matrix', models.CharField(max_length=10000, verbose_name='Matriz')),
                ('motifs', models.CharField(max_length=10000, verbose_name='Motivos')),
                ('reverseComplement', models.CharField(max_length=10000, verbose_name='Complemento reverso')),
            ],
            options={
                'verbose_name': 'Fator de transcrição',
                'verbose_name_plural': 'Fatores de transcrição',
                'ordering': ['family', 'id'],
            },
        ),
    ]
