# Generated by Django 2.1 on 2018-08-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptor',
            name='a',
            field=models.TextField(max_length=10000, verbose_name='A'),
        ),
        migrations.AlterField(
            model_name='transcriptor',
            name='c',
            field=models.TextField(max_length=10000, verbose_name='C'),
        ),
        migrations.AlterField(
            model_name='transcriptor',
            name='g',
            field=models.TextField(max_length=10000, verbose_name='G'),
        ),
        migrations.AlterField(
            model_name='transcriptor',
            name='matrix',
            field=models.TextField(max_length=10000, verbose_name='Matriz'),
        ),
        migrations.AlterField(
            model_name='transcriptor',
            name='t',
            field=models.TextField(max_length=10000, verbose_name='T'),
        ),
    ]
